# Generated by Django 4.1.3 on 2022-12-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20221201_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='privilege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privelege_chatmembers', to='chats.memberprivilege', verbose_name='Привелегия'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chats.chat', verbose_name='Чат сообщения'),
        ),
    ]
